### ISSUE TITLE
[BUG] Root Url error

### ISSUE THREAD

**Issue by RogerTangos** [VertaAI/modeldb#212]
`http://localhost:3000/`

First noticed at 152a63a404cad5344b1f3acc5a6012c6d915b64b
Bug not present at dea76048e309b1c60772c11bfab735c5275d444e

```
TypeError: api.testConnection is not a function
    at /Users/arcarter/code/modeldb/frontend/routes/index.js:7:7
    at Layer.handle [as handle_request] (/Users/arcarter/code/modeldb/frontend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/arcarter/code/modeldb/frontend/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/arcarter/code/modeldb/frontend/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/arcarter/code/modeldb/frontend/node_modules/express/lib/router/layer.js:95:5)
    at /Users/arcarter/code/modeldb/frontend/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/arcarter/code/modeldb/frontend/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/arcarter/code/modeldb/frontend/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/arcarter/code/modeldb/frontend/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/arcarter/code/modeldb/frontend/node_modules/express/lib/router/index.js:46:12)
```

**Comment by weienlee** [comment]
issue fixed in this [commit](https://github.com/mitdbg/modeldb/commit/6d31481c639fbd4a90a6b6e391b3ec8bdb2a0e61)
