### ISSUE TITLE
Fix Python Pipeline Tests

### ISSUE THREAD

**Issue by RogerTangos** [VertaAI/modeldb#237]
Two of the python tests have been failing for some time now. Could someone please take a look at these and either fix the test or what they're testing? I'm not really familiar enough with it to do it myself.

[`testPipelineEvent.test_overall_pipeline_fit_event`](https://github.com/mitdbg/modeldb/blob/master/client/python/modeldb/tests/sklearn/testPipelineEvent.py#L57) and [`testPipelineEvent.test_pipeline_first_fit_stage`](https://github.com/mitdbg/modeldb/blob/master/client/python/modeldb/tests/sklearn/testPipelineEvent.py#L1147)

```
======================================================================
FAIL: test_overall_pipeline_fit_event (testPipelineEvent.TestPipelineEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testPipelineEvent.py", line 105, in test_overall_pipeline_fit_event
    utils.is_equal_transformer_spec(spec, expected_spec, self)
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/utils.py", line 153, in is_equal_transformer_spec
    tester.assertEqual(len(spec1.hyperparameters), len(spec2.hyperparameters))
AssertionError: 14 != 10

======================================================================
FAIL: test_pipeline_first_fit_stage (testPipelineEvent.TestPipelineEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testPipelineEvent.py", line 149, in test_pipeline_first_fit_stage
    utils.is_equal_transformer_spec(spec, expected_spec, self)
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/utils.py", line 153, in is_equal_transformer_spec
    tester.assertEqual(len(spec1.hyperparameters), len(spec2.hyperparameters))
AssertionError: 7 != 3

```

**Comment by RogerTangos** [comment]
This is due to differing versions of sklearn. Resolved in #240 by adding [`scikit-learn==0.17.1`](https://github.com/mitdbg/modeldb/pull/240/files#diff-38163dc71e44bc1a69dff51ab2d57f7fR9)
