### ISSUE TITLE
Error in ModelDbSyncer line number 268

### ISSUE THREAD

**Issue by vidit-bhatia** [VertaAI/modeldb#265]
`Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.2.1\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.2.1\helpers\pydev\pydevd.py", line 1023, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2017.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/vibhatia/PycharmProjects/modeldbexample/demo/linearmodel.py", line 34, in <module>
    df, target, test_size=0.3)
  File "C:\Users\vibhatia\AppData\Local\Programs\Python\Python35\lib\site-packages\modeldb\sklearn_native\ModelDbSyncer.py", line 258, in train_test_split_fn
    result = split_dfs[:len(split_dfs) / 2]
TypeError: slice indices must be integers or None or have an __index__ method`

After changing the line to result = split_dfs[:int(len(split_dfs) / 2)] It works I am using python 3.5 . Lemme know if this works and I can make the change and do a pull request

**Comment by justinanderson** [comment]
Hi @vidit-bhatia, have you tried the RogerTangos/Python3 branch? The master branch is Python 2 only at the moment, and the change you suggest has already been made in the Python 3 branch. I'm not sure when the Python 3 branch will be merged.
