### ISSUE TITLE
Got a 404 response when do create_registered_model

### ISSUE THREAD

**Issue by LuBingtan** [VertaAI/modeldb#2656]
## What happened
My python code:
```python
from verta import Client
client = Client("http://localhost:3000")
reg_model = client.create_registered_model("my-model-name")
```

And then I got this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/verta/client.py", line 1095, in create_registered_model
    public_within_org=public_within_org, visibility=visibility,
  File "/usr/local/lib/python3.6/dist-packages/verta/tracking/entities/_entity.py", line 175, in _create
    msg = cls._create_proto(conn, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/verta/tracking/entities/_entity.py", line 200, in _create_proto
    return cls._create_proto_internal(conn, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/verta/registry/entities/_model.py", line 714, in _create_proto_internal
    registered_model = conn.must_proto_response(response, _RegistryService.SetRegisteredModel.Response).registered_model
  File "/usr/local/lib/python3.6/dist-packages/verta/_internal_utils/_utils.py", line 114, in must_proto_response
    raise_for_http_error(response)
  File "/usr/local/lib/python3.6/dist-packages/verta/_internal_utils/_utils.py", line 455, in raise_for_http_error
    six.raise_from(requests.HTTPError(message, response=response), None)
  File "<string>", line 3, in raise_from
requests.exceptions.HTTPError: 404 Client Error: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /api/v1/registry/workspaces/personal/registered_models</pre>
</body>
</html> for url: http://localhost:3000/api/v1/registry/workspaces/personal/registered_models at 2021-09-27 07:08:36.823000 UTC
```

## Deployment environment
- docker version: 20.10.5
- modeldb frontend image: 2.0.8.2
- modeldb graphql image: 2.0.8.1
- modeldb proxy image: 2.0.8.1
- modeldb backend image: 2.0.8.1

**Comment by convoliution** [comment]
Hello @LuBingtan, thank you for your interest in our platform.

The model registry is not currently available in our open-source platform, which is why the client is returning these `404`s. If you'd like, please feel free to contact us for information about our SaaS offering—we'd also love to hear about the usecase you have in mind.

https://www.verta.ai/contact/

**Comment by LuBingtan** [comment]
> Hello @LuBingtan, thank you for your interest in our platform.
> 
> The model registry is not currently available in our open-source platform, which is why the client is returning these `404`s. If you'd like, please feel free to contact us for information about our SaaS offering—we'd also love to hear about the usecase you have in mind.
> 
> https://www.verta.ai/contact/

I see. Thanks for the reply : )
