### ISSUE TITLE
Creating annotations give 500 Error

### ISSUE THREAD

**Issue by vidit-bhatia** [VertaAI/modeldb#267]
When I try to create some annotations on a model it gives us 500 error

```javascript
Transformer is not defined
ReferenceError: Transformer is not defined
    at Object.storeAnnotation (E:\machinelearning\git\modeldb\frontend\util\api.js:109:27)
    at E:\machinelearning\git\modeldb\frontend\routes\models.js:30:7
    at Layer.handle [as handle_request] (E:\machinelearning\git\modeldb\frontend\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\machinelearning\git\modeldb\frontend\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (E:\machinelearning\git\modeldb\frontend\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\machinelearning\git\modeldb\frontend\node_modules\express\lib\router\layer.js:95:5)
    at E:\machinelearning\git\modeldb\frontend\node_modules\express\lib\router\index.js:277:22
    at param (E:\machinelearning\git\modeldb\frontend\node_modules\express\lib\router\index.js:349:14)
    at param (E:\machinelearning\git\modeldb\frontend\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (E:\machinelearning\git\modeldb\frontend\node_modules\express\lib\router\index.js:410:3)
```

![image](https://user-images.githubusercontent.com/3845645/30597195-27bb93fc-9d0b-11e7-9d8f-1e903de6fadf.png)
#268

**Comment by vidit-bhatia** [comment]
@mpvartak closing this as this issue is resolved in master and already merged
