### ISSUE TITLE
Manage model dependencies doesn't work(logEnvironment 404)

### ISSUE THREAD

**Issue by Wilsonkongcheng** [VertaAI/modeldb#3730]
When I  run this script in your doc [https://docs.verta.ai/verta/experiment-management/guides/env-variables](https://docs.verta.ai/verta/experiment-management/guides/env-variables) ,it raise the 404 error.Does it mean  open-source docker platform can't support it anymore?
```
from verta import Client
client = Client("http://localhost:3000")
from verta.environment import Python
run.log_environment(
    Python(
        requirements=[
            "scikit-learn==0.23.2",
            "pandas",  # gets version pin from current environment
        ],
        env_vars={"OMP_NUM_THREADS": "4"},
    ),
    overwrite=True,
)


Traceback (most recent call last):
  File "F:\PycharmProject\modeldb\test_2.py", line 25, in <module>
    run.log_environment(
  File "C:\Users\63439\anaconda3\envs\modeldb\lib\site-packages\verta\tracking\entities\_experimentrun.py", line 1764, in log_environment
    _utils.raise_for_http_error(response)
  File "C:\Users\63439\anaconda3\envs\modeldb\lib\site-packages\verta\_internal_utils\_utils.py", line 555, in raise_for_http_error
    six.raise_from(requests.HTTPError(message, response=response), None)
  File "<string>", line 3, in raise_from
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:3000/api/v1/modeldb/experiment-run/logEnvironment at 2023-04-07 08:08:40.383000 UTC
```

**Comment by liuverta** [comment]
Hi @Wilsonkongcheng, that is correct—`/logEnvironment` is not currently available in our open-source platform.

If you're interested in versioning/cataloguing models and their Python environments, please feel free to contact us through our support page (https://www.verta.ai/contact-us) and we might able to recommend other solutions for your use case!
