### ISSUE TITLE
run.log_model(model) and get ValueError: path is on mount 'c:', start on mount 'D:'

### ISSUE THREAD

**Issue by loveunk** [VertaAI/modeldb#637]
Error happens during executing `run.log_model(model)`:

```shell
Git repository successfully located at D:/code/ai_tools_benchmark\
Traceback (most recent call last):
  File "modeldb_pytorch_integration.py", line 156, in <module>
    main()
  File "modeldb_pytorch_integration.py", line 149, in main
    run.log_model(model)
  File "D:\Anaconda3\envs\open-mmlab\lib\site-packages\verta\client.py", line 3031, in log_model
    self._log_modules(custom_modules, overwrite=overwrite)
  File "D:\Anaconda3\envs\open-mmlab\lib\site-packages\verta\client.py", line 3477, in _log_modules
    depl_sys_paths = list(map(lambda path: os.path.relpath(path, common_dir), local_sys_paths))
  File "D:\Anaconda3\envs\open-mmlab\lib\site-packages\verta\client.py", line 3477, in <lambda>
    depl_sys_paths = list(map(lambda path: os.path.relpath(path, common_dir), local_sys_paths))
  File "D:\Anaconda3\envs\open-mmlab\lib\ntpath.py", line 562, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'c:', start on mount 'D:'
```

My OS is windows 10 and `modeldb` is deployed on this machine.

Looking forward to your help. Thanks.

**Comment by convoliution** [comment]
Hi @loveunk

The ModelDB Client currently has limited support for Windows; I'll check in with the rest of our team here, and get back to you when we have an update!

**Comment by loveunk** [comment]
@convoliution no problem, thank you.
